version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost/:/etc/nginx/vhost.d:ro
      - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./static/:/code/static/
      - ./media/:/code/media/

  postgres:
    image: postgres
    volumes:
      - ./postgresdb/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ./.envv

  web:
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - "postgres"
    env_file: ./.envv
    container_name: web

  celery: 
    build: 
      context: .
      dockerfile: celery.dockerfile
    volumes:
      - .:/code
    links:
      - redis
      - postgres
    depends_on: 
      - "redis"
      - "postgres"
    env_file: ./.env
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD
    restart: "always"
    env_file: ./.env